#!/bin/sh
# Install hist-event-reaction, gathering history data from all users into a log with timestamps of when the data was gathered.
echo "To use live history logging with timestamps, set the user to:"
echo "export HISTCONTROL=ignoredups:erasedups"
echo "shopt -s histappend"
echo "export PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}history -a; history -c; history -r""
echo ""
echo "################################################################################################"
echo ""
echo "If you don't set the above options, your data will be based on the writes to the history logs..."
echo ""
echo "Now lets get things set up and the daemon running..."
which wget
if [ $? -eq 0 ]; then
echo "Found wget, which we use to pull back down data from the web that gets deleted."
else
echo "Please install wget before running this script again."
exit 1
fi
if [ -f /usr/local/bin/sec.pl ] ; then
echo "Found /usr/local/bin/sec.pl"
else
echo "Installing /usr/local/bin/sec.pl"
wget http:/hyalitepress.com/sec
if [ whoami == root ]; then
echo "Running as root."
cp sec /usr/local/bin/sec.pl
chmod +x /usr/local/bin/sec.pl
else
echo "Running as $(whoami)";
cp sec /usr/local/bin/sec.pl
if [ $? -eq 0 ]; then
echo "Configured sec as $(whoami)"
else
echo "Failed to configure sec as $(whoami).... trying sudo."
sudo cp sec /usr/local/bin/sec.pl
if [ $? -eq 0 ]; then
echo "Configured sec as $(whoami) with sudo."
else
echo "Could not install sec.pl, please run with permissions to write to /usr/local/bin"
fi
fi
fi
fi
echo "Alright, now that we have the dependancies, moving on to the hist-event-reaction configuration...."
if [ whoami == root ]; then
echo "Running as root."
echo "Setting up directories..."
mkdir -p /opt/hist-event-reaction/etc/
mkdir -p /opt/hist-event-reaction/bin/
echo "Setting up a local bin of the init script"
chmod +x hist-event-reaction 
cp hist-event-reaction /usr/local/bin/
echo "Looking for hist-event-reaction.conf"
ls hist-event-reaction.conf
cp hist-eent-reaction.conf /opt/hist-event-reaction/etc/
echo "Configured hist-event-reaction.conf"
else
echo "Running as $(whoami)";
echo "Setting up directories..."
mkdir -p /opt/hist-event-reaction/etc/
mkdir -p /opt/hist-event-reaction/bin/
echo "Setting up a local bin of the init script"
chmod +x hist-event-reaction 
cp hist-event-reaction /usr/local/bin
if [ $? -eq 0 ]; then
echo "Set up directories as $(whoami)"
else
echo "Couldn't set up directories /opt/hist-event-reaction/etc and /opt/hist-event-reaction/bin as $(whoami)."
echo "Trying sudo..."
sudo mkdir -p /opt/hist-event-reaction/etc
sudo mkdir -p /opt/hist-event-reaction/bin
if [ $? -eq 0 ]; then
echo "Set up directories as $(whoami) with sudo."
else
echo "Could not set up directories, please run with elevated permissions."
fi
fi
fi
echo "Looking for hist-event-reaction.conf"
ls hist-event-reaction.conf
cp hist-event-reaction.conf /opt/hist-event-reaction/etc/
if [ $? -eq 0 ]; then
echo "Located and install hist-event-reaction.conf as $(whoami)"
else
echo "Failed to install hist-event-reaction.conf as $(whoami).... trying sudo."
sudo cp hist-event-reaction.conf /opt/hist-event-reaction/etc/
if [ $? -eq 0 ]; then
echo "Found and installed hist-event-reaction.conf as $(whoami) with sudo."
else
echo "Could not install sec.pl, please run with permissions to write to /usr/local/bin"
fi
fi
echo "Daemonizing"
if [ whoami == root ]; then
  journaltctl > /opt/hist-event-reaction/etc/journalctl.out &
  sec.pl -detach -reopen_timeout=60 -input=/opt/hist-event-reaction/etc/journalctl.out -input=/root/.bash_history -input=/root/.*history* -input=/home/*/.bash_history -conf=/opt/hist-event-reaction/etc/hist-event-reaction.conf -log=/opt/hist-event-reaction/hist-event-reaction.log
  echo "Daemonized with the pid of:";
  ps -ef | grep "log=/opt/hist-event-reaction/hist-event-reaction.log" | grep -v grep | awk '{print $2}' | tee /var/run/hist-event-reaction.pid
else
  journaltctl > /opt/hist-event-reaction/etc/journalctl.out &
  sudo sec.pl -detach -reopen_timeout=60 -input=/opt/hist-event-reaction/etc/journalctl.out -input=/root/.bash_history -input=/root/.*history* -input=/home/*/.bash_history -conf=/opt/hist-event-reaction/etc/hist-event-reaction.conf -log=/opt/hist-event-reaction/hist-event-reaction.log
  echo "Daemonized with the pid of:";
  ps -ef | grep "log=/opt/hist-event-reaction/hist-event-reaction.log" | grep -v grep | awk '{print $2}'
fi
